### ISSUE TITLE
Port API: support specifying IP version explicitly ("tcp4", "tcp6")

### ISSUE THREAD

**Issue by AkihiroSuda** [rootless-containers/rootlesskit#231]
The new version of Docker libnetwork executes two proxy commands: https://github.com/moby/moby/pull/41908#issuecomment-786417555

```bash
rootlesskit-docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8080 -container-ip 172.17.0.2 -container-port 80
rootlesskit-docker-proxy -proto tcp -host-ip :: -host-port 8080 -container-ip 172.17.0.2 -container-port 80
```

`rootlesskit-docker-proxy` now fails with EADDRINUSE bcause it cause the equivalent of `rootlessctl add-ports 0.0.0.0:8080:80/tcp [::]:8080:80/tcp`
```console
$ rootlessctl add-ports 0.0.0.0:8080:80/tcp [::]:8080:80/tcp
1
error: listen tcp 0.0.0.0:8080: bind: address already in use
```

`rootlesskit-docker-proxy` probably needs to be modified to cause `rootlessctl add-ports 0.0.0.0:8080:80/tcp4 [::]:8080:80/tcp6`

cc @thaJeztah @arkodg

**Comment by AkihiroSuda** [comment]
Implementing this is straightforward for `builtin` port driver (the default of rootless docker), but the problem is that `slirp4netns` port driver does't support IPv6 yet (https://github.com/rootless-containers/slirp4netns/issues/253).

Should `rootlesskit-docker-proxy` ignore `-host-ip ::` when the port driver is set to slirp4netns?
Or can we configure `dockerd` to skip invoking the proxy with `-host-ip ::`?

**Comment by thaJeztah** [comment]
> Or can we configure dockerd to skip invoking the proxy with -host-ip ::?

It's tricky; so before docker 20.10, publishing a port to listen on "any" IP (`-p 80:80` or `-p 0.0.0.0:80:80`) implicitly made the port available on _both_ IPv4 and IPv6.

That most likely was an oversight in the original implementation; docker 20.10 "fixed" that, by no longer publishing on IPv6 by default, but there's many people relying on the (faulty?) behaviour, and assume that `-p 80:80` makes the port accessible, irregardless if I try IPv4 or IPv6 (which also makes sense).

The libnetwork update attempts to fix the situation, but instead of "implicitly" exposing both on IPv4 and IPv6 now _explicitly_ exposes on both, which shows both in `docker inspect` of the container, but also (as a "side-effect" ?) starts two proxies.

I'm a bit on the fence what the best solution is (also a bit worried about (by default) starting two proxies now, as there could be a non-neglectible overhead in that)

**Comment by AkihiroSuda** [comment]
Opened PR https://github.com/rootless-containers/rootlesskit/pull/232

When the port driver is set to slirp4netns, `docker run -p [v6]:8080:80` skips exposing the port, without showing an error.
This behavior might be weird, but I think we can call it a day. ("slirp4netns" port driver is not used by default, even when the network driver is set to "slirp4netns".)

The default port driver `builtin` seems now fully functional with IPv6.
