### ISSUE TITLE
rootless docker works only for one user

### ISSUE THREAD

**Issue by eschen42** [rootless-containers/rootlesskit#56]
When working with https://get.dockerless.com/rootless I found that only one user could run the docker service at a time.  The reason is that the first to write /tmp/go.pcap was the owner of that file, and because other users could not write it (because of they did not own it), they could not start docker.

I opened pull request #55 demonstrating a possible solution to this issue (which I implemented on my system to work around this issue).

**Comment by AkihiroSuda** [comment]
A workaround is to install slirp4netns instead of VPNKit

**Comment by eschen42** [comment]
I'm afraid that I don't understand.  `apt search slirp4netns` gets no hits.

**Comment by AkihiroSuda** [comment]
https://github.com/rootless-containers/slirp4netns

v0.2.x is available on Debian 10 apt but rootless Docker requires v0.3.x

**Comment by pathros** [comment]
I have thought of Linux Groups so that multiple Linux Users could execute Docker rootless mode.

My idea is to create a new user, say, "rootless" with a group of the same name "rootless". Then, you would add as many users as you want to that group, so that all the users belonging to that group could execute Docker rootless mode.

Is that approach possible? Or what have you done to execute docker rootless for multiple users.

**Comment by samdwar1976** [comment]
I have a use case where the volume mounted to rootless docker container cannot change and is never uid=1000 or gid=1000. And because I cannot created another user nor change uid of rootless, I am hitting a blocker. Is there anyway to proceed without having to change volume permission as host user needs permissions to stay same to access it

**Comment by AkihiroSuda** [comment]
The OP was about that /tmp/go.pcap was hard-coded in vpnkit. This issue was already resolved in 2019.

Locking this issue to avoid other topics to be mixed up here.
GID management and volumes should be discussed in a different issue.

> Or what have you done to execute docker rootless for multiple users.

Just create subuid and subgid for multiple users

> Is there anyway to proceed without having to change volume permission as host user needs permissions to stay same to access it

I don’t understand your question, but generally you don’t need to change permission of anything.
